spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: postgres
    password: postgres

logging:
  level:
    org.springframework:
      orm.jpa: INFO
      transaction: INFO
      transaction.interceptor: TRACE
      orm.jpa.JpaTransactionManager: DEBUG

---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:shareit
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    path: /h2-console